service: degiro-lambda-bot

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  dotenv:
    required:
      file: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 30
  region: eu-central-1
  profile: degiro-lambda-bot
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  autoBuy:
    handler: src/autoBuy.handler
    events:
      - eventBridge:
          # https://docs.aws.amazon.com/eventbridge/latest/userguide/scheduled-events.html#cron-expressions
          schedule: cron(${env:AUTOBUY_CRON_STRING})
